// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:93979318-836a-4059-a62d-e193cb3275e0",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_x1GNHIP4D",
    "aws_user_pools_web_client_id": "7v1ji36uglhbdvffikost5gljg"
};


export default awsmobile;
