// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:dc5de379-e38a-4e5d-98a1-449fb5124291",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_VjeWB6z6p",
    "aws_user_pools_web_client_id": "45qmrg8psvik1upsfklln0rgat"
};


export default awsmobile;
